### ISSUE TITLE
Integrate a Reporting Tool

### ISSUE THREAD

**Issue by ElSnoMan** [ElSnoMan/pyleniumio#131]
## Description

Pylenium has built-in ReportPortal.io (RP) **_support_**, but RP can be difficult for some to set up since it requires multiple services. Maybe we could integrate our own reporting solution into Pylenium instead! The best option, besides building our own, looks like Allure.

Right now, we don't really have a **_"fully built-in"_** reporter and leave that up to the User. I think it's valuable to allow the User to choose their preferred reporter, but I also think it's helpful to have a "standard" reporter that comes with Pylenium out of the box. We should provide both!

## pytest-html-reporter ❌ 

https://pypi.org/project/pytest-html-reporter/

The biggest pro is that it requires zero setup. However, it doesn't have rich reporting like Allure or Report Portal. With it being so easy to setup, if a Pylenium User wants to use it, they can simply install the addon and use it!

## allure-pytest ✅ 

The problem with Allure, similar to Report Portal, is that it requires installing their CLI client or Docker Image to use. However, the setup is _much easier_ than Report Portal AND they have rich reporting which I believe makes it our solid go-to.

Github Repo:
https://github.com/allure-framework/allure2

Official Docs:
https://docs.qameta.io/allure/

allure-pytest plugin Docs:
https://docs.qameta.io/allure/#_pytest

### Step 1: Install Allure CLI

Docker Image
https://hub.docker.com/r/frankescobar/allure-docker-service

Official Allure with Docker Repo
https://github.com/fescobar/allure-docker-service#docker-hub

Different options depending on OS:
https://docs.qameta.io/allure/#_installing_a_commandline

### Step 2: Run Tests with Allure

```bash
pytest --alluredir=./allure-report
```

### Step 3: View Allure Report

```bash
allure serve ./allure-report
```

with Docker

```bash
docker run -p 5050:5050 -e CHECK_RESULTS_EVERY_SECONDS=3 -e KEEP_HISTORY=1 \
                 -v ${PWD}/allure-results:/app/allure-results \
                 -v ${PWD}/allure-reports:/app/default-reports \
                 frankescobar/allure-docker-service
```

## Tasks

> V1: make the installation of `allure` required by the User

- [x] Add allure to pyproject.toml
- [x] Add Pylenium commands to make using allure easier
- [x] Add new reporting documentation (see #292)

### Add allure to pyproject.toml

Just by installing allure's pytest plugin, you get tons of functionality right out of the box that works well with how Pylenium is already setup! For example:

- Logs are already captured and sent to the report
- Fixtures and finalizers are handled and sent to the report as well
- Screenshots on test failure were a single line change
- and more!

If the user wants even more functionality, like take screenshots per step or categorizing tests, then they can leverage pytest's existing features (ie parameterization) or use allure directly (ie record each step in a test). For example:

```py
import allure
import pytest


@allure.step
def simple_step(step_param1, step_param2 = None):
    pass


@pytest.mark.parametrize('param1', [True, False], ids=['id explaining value 1', 'id explaining value 2'])
def test_parameterize_with_id(param1):
    simple_step(param1)
```

### Add Pylenium commands to make using allure easier

As you saw in the previous section, pytest and allure work together extremely well, so there wasn't much for us to add to Pylenium besides taking screenshots on failure and uploading it to the appropriate test.

However, I did add three commands that are more for convenience than anything:

- `$ pylenium allure install` - Executes the recommended installation commands for your operating system
- `$ pylenium allure check` - Checks that allure is installed, on the PATH, and displays the version if installed correctly
- `$ pylenium allure serve [FOLDER]` - Starts the allure server and serves the report using the given folder

☝🏽 Each of these commands displays the command(s) they execute so the user knows what's happening behind the scenes. For the installation commands, a `Would you like to proceed?` prompt is given so they can see what's about to be executed and choose to proceed or not.

### Add new reporting documentation

Hopefully self-explanatory. We should have helpful docs for users to know how to setup allure reporting, official resources, and of course, how to generate and view reports. The initial guides will be simple, but we can add more advanced scenarios later on.
